### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by dananas** [pavoltanuska/miro-estimate#1]
I didn't find your social network account, so decided to write to you here.
Just wanted to say that In my opinion your work worth a first place, nice work :)

**Comment by pavoltanuska** [comment]
Thanks for reaching out and opening the first issue, such words from a fellow competitor mean a lot to me!

I like your take on the [color palette](https://github.com/dananas/color-palette), it gives me a very nice overview of what's happening with all the colors on my board.

Do you plan to develop it further? Your code looks clean and well structured (I can definitely learn a thing or two from you), so the maintenance should be easy enough :)
